import React,{useState} from 'react';
import {proportionExperiment,randomizationDifferences,randomizationP,proportionInterval,formatP,type ABResult} from '../../../reading-src/lib/statistics/course-models';
import DistributionPlot from './DistributionPlot';
export default function ABExperiment(){
 const [n,setN]=useState(50),[effect,setEffect]=useState(.1),[data,setData]=useState<ABResult|null>(null),[draws,setDraws]=useState<number[]>([]);
 function reset(){setData(null);setDraws([]);}
 const observed=data?(data.b-data.a)/data.n:0,interval=data?proportionInterval(data):null;
 return <section className="stats-lab bg-zinc-800 rounded-lg p-5 mb-8 callout" id="ab-lab" aria-label="Compare two proportions">
  <p className="stats-eyebrow">Two versions of a sign-up page</p><p>Each visitor receives exactly one randomly assigned version, A or B; the outcome is whether they sign up. This simulated world has sign-up probability 30% for A. You control B’s true difference.</p>
  <div className="stats-settings"><label className="stats-control">Visitors per group<select aria-label="A/B sample size" value={n} onChange={e=>{setN(Number(e.target.value));reset();}}>{[20,50,100].map(v=><option value={v} key={v}>{v}</option>)}</select></label><label className="stats-control">True B − A difference<select aria-label="A/B true difference" value={effect} onChange={e=>{setEffect(Number(e.target.value));reset();}}>{[0,.1,.2].map(v=><option value={v} key={v}>{100*v} percentage points</option>)}</select></label></div>
  <div className="stats-actions"><button type="button" onClick={()=>{setData(proportionExperiment(n,effect));setDraws([]);}}>Simulate an A/B study</button><button type="button" disabled={!data} onClick={()=>data&&setDraws([...draws,...randomizationDifferences(data,500)].slice(-10000))}>Shuffle labels 500 times</button></div>
  {data?<><table><caption>Observed sign-ups</caption><thead><tr><th scope="col">Group</th><th scope="col">Sign-ups / visitors</th><th scope="col">Sign-up proportion</th></tr></thead><tbody><tr><th scope="row">A</th><td>{data.a} / {n}</td><td>{(100*data.a/n).toFixed(1)}%</td></tr><tr><th scope="row">B</th><td>{data.b} / {n}</td><td>{(100*data.b/n).toFixed(1)}%</td></tr></tbody></table><p>Observed B − A: <strong>{(100*observed).toFixed(1)} percentage points</strong>. The simulation’s true difference is {100*effect} points.</p>{interval?<p>Approximate 95% interval for B − A: <strong>{(100*interval.low).toFixed(1)} to {(100*interval.high).toFixed(1)} percentage points</strong>. This uses the large-sample, unpooled standard error for two independent proportions.</p>:<p className="stats-small">At least one group has fewer than ten sign-ups or ten non-sign-ups. The large-sample interval is withheld; use a larger planned sample or an interval method suited to small counts. The label-shuffling test below does not require those count conditions.</p>}</>:<p>No study yet. Predict whether one study’s observed difference will equal the true difference.</p>}
  <p>For the randomization test, keep every observed sign-up and non-sign-up fixed. Shuffle them between equally sized groups, as if assignment had no effect on anyone’s outcome. Count shuffled differences at least as far from zero as the observed difference, in <strong>either direction</strong>.</p>
  <DistributionPlot values={draws.map(x=>100*x)} min={-100} max={100} bins={40} title="Differences after shuffling under no effect" unit="B − A (percentage points)" marker={data?{value:100*observed,label:'observed difference'}:undefined}/>
  <p role="status">{draws.length.toLocaleString('en-US')} shuffled assignments.{draws.length>0&&` Two-sided Monte Carlo p-value: ${formatP(randomizationP(draws,observed))}.`}</p>
  <p className="stats-small">At most the latest 10,000 shuffles are retained. The Monte Carlo calculation is (extreme shuffles + 1) / (shuffles + 1), so finite simulation never claims a zero p-value. A new study or setting clears the old reference distribution.</p>
 </section>;
}
