import React,{useState} from 'react';
export default function ExperimentDesigner(){
 const [unit,setUnit]=useState('student'),[assignment,setAssignment]=useState('choice'),[outcome,setOutcome]=useState('fixed'),[reviewed,setReviewed]=useState(false);
 function revise(set:(v:string)=>void,value:string){set(value);setReviewed(false);}
 return <section className="stats-lab bg-zinc-800 rounded-lg p-5 mb-8 callout" id="design-lab" aria-label="Plan a classroom experiment">
  <p className="stats-eyebrow">Choose the design before seeing the scores</p><p>Twelve classrooms have 20 students each. Teachers will deliver either a new lesson or the usual lesson to their entire class for four weeks. Your question: does the new lesson change the mean score on a common final quiz?</p>
  <label className="stats-control">What receives an independently assigned lesson?<select aria-label="Assignment unit" value={unit} onChange={e=>revise(setUnit,e.target.value)}><option value="student">Each of the 240 students</option><option value="class">Each of the 12 classrooms</option></select></label>
  <label className="stats-control">How do we allocate the lessons?<select aria-label="Lesson allocation" value={assignment} onChange={e=>revise(setAssignment,e.target.value)}><option value="choice">Let teachers choose</option><option value="random">Randomize six classrooms per lesson</option><option value="blocked">Randomize within matched pairs</option></select></label>
  <label className="stats-control">Which result do we report?<select aria-label="Primary outcome rule" value={outcome} onChange={e=>revise(setOutcome,e.target.value)}><option value="fixed">Preselect one quiz and endpoint</option><option value="best">Report the largest of several results</option></select></label>
  <div className="stats-actions"><button type="button" onClick={()=>setReviewed(true)}>Review this plan</button></div>
  {reviewed&&<div className="stats-feedback" aria-live="polite"><h3>Review of your plan</h3><p>{unit==='class'?'The assignment units are the 12 classrooms. Students supply measurements within those units; they do not create 240 independent treatment assignments.':'The teacher delivers one lesson to an entire class, so you cannot independently assign each student in this scenario. The actual assignment units are the 12 classrooms.'}</p><p>{assignment==='choice'?'Teacher choice can entangle the lesson with preparation, motivation, or classroom resources. A later difference would not isolate the lesson’s effect.':assignment==='random'?'Random assignment makes the classroom groups comparable on average. Analyze the six classroom means per group, or use a method that accounts for clustering.':'Pair classrooms using baseline quiz scores before assignment. Matching makes that similarity part of the design. Randomize one classroom in each pair to each lesson, then analyze the six paired differences between classroom means.'}</p><p>{outcome==='fixed'?'A fixed primary outcome and endpoint keep the question aligned with the reported analysis. Also specify exclusions and how missing quiz scores will be handled before collecting data.':'Selecting the largest result after trying several outcomes changes the testing procedure. Preselect a primary outcome or account for the full set of comparisons.'}</p><p>Use the same quiz and scoring rubric in both arms. Have a scorer who cannot see lesson assignments grade coded answers where feasible. Report missing results and deviations from the plan.</p></div>}
 </section>;
}
