import React,{useState} from 'react';
import {normalPower,powerExperiments} from '../../../reading-src/lib/statistics/course-models';
import DistributionPlot from './DistributionPlot';
export default function PowerLab(){
 const [effect,setEffect]=useState(5),[n,setN]=useState(25),[alpha,setAlpha]=useState(.05),[tests,setTests]=useState(1);
 const [results,setResults]=useState<ReturnType<typeof powerExperiments>>([]);
 const rejects=results.filter(r=>r.reject).length,planned=normalPower(effect,n,alpha);
 return <section className="stats-lab bg-zinc-800 rounded-lg p-5 mb-8 callout" id="power-lab" aria-label="Power and error experiment">
  <p className="stats-eyebrow">One study can miss; many studies reveal the method</p><p>Each study compares two independent normal populations with known standard deviation 10 points. The test asks whether their means differ in either direction. You know the true difference because you set this simulated world.</p>
  <div className="stats-settings"><label className="stats-control">True difference<select aria-label="True effect" value={effect} onChange={e=>{setEffect(Number(e.target.value));setResults([]);}}>{[0,2,5,10].map(v=><option value={v} key={v}>{v} points</option>)}</select></label><label className="stats-control">People per group<select aria-label="Power sample size" value={n} onChange={e=>{setN(Number(e.target.value));setResults([]);}}>{[10,25,100].map(v=><option value={v} key={v}>{v}</option>)}</select></label><label className="stats-control">Significance threshold<select aria-label="Significance threshold" value={alpha} onChange={e=>{setAlpha(Number(e.target.value));setResults([]);}}>{[.01,.05,.1].map(v=><option value={v} key={v}>{v}</option>)}</select></label></div>
  <div className="stats-actions"><button type="button" onClick={()=>setResults([...results,...powerExperiments(effect,n,alpha,100)].slice(-10000))}>Run 100 studies</button><button type="button" onClick={()=>setResults([])}>Start over</button></div>
  <p role="status">{results.length.toLocaleString('en-US')} studies. {effect===0?'False positives':'Detected effects'}: {rejects}{results.length?` (${(100*rejects/results.length).toFixed(1)}%)`:''}. {effect!==0&&`Missed effects: ${results.length-rejects}.`}</p>
  <p>The model’s {effect===0?'false-positive rate':'power'} is <strong>{(100*planned).toFixed(1)}%</strong>. Repeating a finite batch need not reproduce that percentage exactly.</p>
  <DistributionPlot values={results.map(r=>r.estimate)} min={-30} max={40} bins={35} title="Estimated differences across studies" unit="Difference (points)" marker={{value:effect,label:'true difference'}}/>
  <p className="stats-small">The calculation uses a two-sided z test because population spread is known in this model. Real mean comparisons usually estimate spread and use t methods. The latest 10,000 studies are retained. The chart covers −30 to 40; any rarer estimate outside that range still counts in the results above.</p>
  <details className="stats-extra"><summary>What if we test many questions?</summary><label className="stats-control">Independent tests, all with true nulls<select aria-label="Number of tests" value={tests} onChange={e=>setTests(Number(e.target.value))}>{[1,5,20].map(v=><option value={v} key={v}>{v}</option>)}</select></label><p>At threshold {alpha}, the chance of at least one false positive across {tests} independent tests is 1 − (1 − {alpha})<sup>{tests}</sup> = <strong>{(100*(1-(1-alpha)**tests)).toFixed(1)}%</strong>. Independence and true nulls are assumptions of this calculation.</p><p>A simple planned family-wise correction tests each of m questions at α/m (Bonferroni). This controls the probability of any false positive at most α for valid individual tests, even when tests are dependent; it can reduce power.</p></details>
 </section>;
}
